routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['prefix' => 'dashboard'], function() {
    Auth::routes([
        'register' => false,
        'reset' => false,
        'verify' => false,
    ]);
});

Route::get('/', 'WebsiteController@index');

Route::group(['middleware' => ['auth'], 'prefix' => 'dashboard'], function () {

    Route::get('/', 'HomeController@index')->name('dashboard');

    /**
     * Profile & User Route
     */
    Route::get('profile', 'UsersController@profile')->name('profile');
    Route::patch('profile/{user}', 'UsersController@profileUpdate')->name('profile.update');
    Route::resource('users', 'UsersController');

    /**
     * Roles & Permissions Administrator Route
     */
    Route::resource('roles', 'RolesController');
    Route::patch('permissions/sort-module', 'PermissionsController@sortModule')->name('permissions.sort-module');
    Route::resource('permissions', 'PermissionsController', ['except' => [
        'create', 'show', 'edit'
    ]]);

    Route::resource('categories', 'CategoriesController');
    Route::resource('books', 'BooksController');

});

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    protected $table = 'books';
    protected $fillable = [
        'category_id',
        'name',
        'price'
    ];

    public function dataCategory() {
        return $this->belongsTo('App\Category', 'category_id', 'id');
    }
}

app/Http/Controllers/BooksController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;

use Illuminate\Http\Request;
use Illuminate\Support\Arr;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Auth;
use Spatie\Permission\Models\Role;

use App\Category;
use App\Book;

use DB;
use Hash;
use Image;
use DataTables;
use Form;

class BooksController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:books-list', ['only' => ['index', 'show']]);
        $this->middleware('permission:books-create', ['only' => ['create', 'store']]);
        $this->middleware('permission:books-edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:books-delete', ['only' => ['destroy']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $books = Book::orderBy('created_at', 'ASC')->get();
        return view('backend.books.index', compact('books'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('backend.books.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name'  => 'required',
            'type'  => 'required',
            'price' => 'required',
        ]);

        Book::create([
            'category_id' => $request->type,
            'name' => $request->name,
            'price' => str_replace(',', '' ,$request->price),
        ]);

        return redirect()->route('books.index')
                        ->with('success', 'Buku berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories = Category::all();
        $book = Book::findOrFail($id);
        return view('backend.books.edit', compact('categories','book'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name'  => 'required',
            'type'  => 'required',
            'price' => 'required',
        ]);

        $book = Book::findOrFail($id);

        $book->update([
            'category_id' => $request->type,
            'name'        => $request->name,
            'price'       => str_replace(',', '' ,$request->price),
        ]);

        return redirect()->route('books.index')
                        ->with('success', 'Buku berhasil diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $book = Book::findOrFail($id);
        $book->delete();
        return response()->json(['status' => true, 'message' => 'Buku berhasil dihapus']);
    }
}

resources/views/backend/books/create.blade.php
@extends('layouts.app')

@section('title', 'Buat Kategori Buku')

@section('styles')
<link rel="stylesheet" href="{{ asset('modules/select2/css/select2.min.css') }}">
@endsection

@section('content')
<div class="section-header">
    <div class="section-header-back">
        <a href="{{ route('categories.index') }}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
    </div>
    <h1>Buat Kategori Buku</h1>
</div>

<div class="section-body">
    <div class="row">
        <div class="col-12">

            {!! Form::open(['method'=>'POST', 'route' => 'books.store', 'autocomplete'=>'off', 'class'=> 'needs-validation', 'novalidate'=> '']) !!}
            <div class="card">
                <div class="card-body">

                    @if (count($errors) > 0)
                      <div class="alert alert-danger">
                        <strong>Whoops!</strong> There were some problems with your input.<br><br>
                        <ul>
                           @foreach ($errors->all() as $error)
                             <li>{{ $error }}</li>
                           @endforeach
                        </ul>
                      </div>
                    @endif

                    <div class="form-group row">
                        <label for="name" class="col-sm-3 col-form-label">Nama Buku</label>
                        <div class="col-sm-9">
                            {!! Form::text('name', null, array('id' => 'name', 'placeholder' => 'Nama Buku', 'class' => 'form-control', 'required', 'autofocus')) !!}
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="type" class="col-sm-3 col-form-label">Tipe Kategori</label>
                        <div class="col-sm-9">
                           <select name="type" id="type" class="form-control" required>
                               @foreach ($categories as $category)
                                <option value="{{ $category->id }}">{{ $category->name }}</option>
                               @endforeach
                           </select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="price" class="col-sm-3 col-form-label">Harga</label>
                        <div class="col-sm-9">
                            {!! Form::text('price', null, array('id' => 'price', 'placeholder' => 'Harga Buku', 'class' => 'form-control', 'required', 'autofocus')) !!}
                        </div>
                    </div>

                </div>
                <div class="card-footer text-right">
                    <button type="submit" class="btn btn-lg btn-primary">Simpan</button>
                </div>
            </div>
            {!! Form::close() !!}

        </div>
    </div>
</div>
@endsection

@section('javascript')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cleave.js/1.6.0/cleave.min.js" integrity="sha512-KaIyHb30iXTXfGyI9cyKFUIRSSuekJt6/vqXtyQKhQP6ozZEGY8nOtRS6fExqE4+RbYHus2yGyYg1BrqxzV6YA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
    $(function(){
        @if ($message = Session::get('success'))
            toastr.success('{{ $message }}', 'Success');
        @endif


        var cleave = new Cleave('#price', {
            numeral: true,
            numeralThousandsGroupStyle: 'thousand'
        });
    });
    </script>
@endsection

resources/views/backend/books/edit.blade.php
@extends('layouts.app')

@section('title', 'Buat Kategori Buku')

@section('styles')
<link rel="stylesheet" href="{{ asset('modules/select2/css/select2.min.css') }}">
@endsection

@section('content')
<div class="section-header">
    <div class="section-header-back">
        <a href="{{ route('categories.index') }}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
    </div>
    <h1>Edit Buku</h1>
</div>

<div class="section-body">
    <div class="row">
        <div class="col-12">

            {!! Form::model($book, ['method' => 'PATCH', 'route' => ['books.update', $book->id], 'autocomplete'=>'off', 'class'=> 'needs-validation', 'novalidate'=> '']) !!}
            <div class="card">
                <div class="card-body">

                    @if (count($errors) > 0)
                      <div class="alert alert-danger">
                        <strong>Whoops!</strong> There were some problems with your input.<br><br>
                        <ul>
                           @foreach ($errors->all() as $error)
                             <li>{{ $error }}</li>
                           @endforeach
                        </ul>
                      </div>
                    @endif

                    <div class="form-group row">
                        <label for="name" class="col-sm-3 col-form-label">Nama Buku</label>
                        <div class="col-sm-9">
                            {!! Form::text('name', null, array('id' => 'name', 'placeholder' => 'Nama Buku', 'class' => 'form-control', 'required', 'autofocus')) !!}
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="type" class="col-sm-3 col-form-label">Tipe Kategori</label>
                        <div class="col-sm-9">
                           <select name="type" id="type" class="form-control" required>
                               @foreach ($categories as $category)
                                <option value="{{ $category->id }}" @if($category->id == $book->category_id) selected @endif >
                                    {{ $category->name }}
                                </option>
                               @endforeach
                           </select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="price" class="col-sm-3 col-form-label">Harga</label>
                        <div class="col-sm-9">
                            {!! Form::text('price', null, array('id' => 'price', 'placeholder' => 'Harga Buku', 'class' => 'form-control', 'required', 'autofocus')) !!}
                        </div>
                    </div>

                </div>
                <div class="card-footer text-right">
                    <button type="submit" class="btn btn-lg btn-primary">Simpan</button>
                </div>
            </div>
            {!! Form::close() !!}

        </div>
    </div>
</div>
@endsection

@section('javascript')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cleave.js/1.6.0/cleave.min.js" integrity="sha512-KaIyHb30iXTXfGyI9cyKFUIRSSuekJt6/vqXtyQKhQP6ozZEGY8nOtRS6fExqE4+RbYHus2yGyYg1BrqxzV6YA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script type="text/javascript">
    $(function(){
        @if ($message = Session::get('success'))
            toastr.success('{{ $message }}', 'Success');
        @endif

        var cleave = new Cleave('#price', {
            numeral: true,
            numeralThousandsGroupStyle: 'thousand'
        });
    });
    </script>
@endsection

resources/views/backend/books/index.blade.php
@extends('layouts.app')

@section('title', 'Buku')

@section('styles')
<link rel="stylesheet" href="{{ asset('modules/datatables/datatables.min.css') }}">
<link rel="stylesheet" href="{{ asset('modules/datatables/datatables/css/dataTables.bootstrap4.min.css') }}">
@endsection

@section('content')
<div class="section-header">
    <h1>Buku</h1>

    @can('books-create')
        <div class="section-header-button ml-auto">
            <a class="btn btn-primary" href="{{ route('books.create') }}">
                Buat Buku
            </a>
        </div>
    @endcan
</div>

<div class="section-body">

    <div class="row">
        <div class="col-12">

            <div class="card">
                <div class="card-body">

                    <div class="table-responsive">
                        <table class="table table-striped" id="table-data">
                            <thead>
                                <tr>
                                    <th width="5%">#</th>
                                    <th>Nama Buku</th>
                                    <th>Kategori Buku</th>
                                    <th>Harga</th>
                                    <th width="20%">&nbsp;</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($books as $book)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $book->name }}</td>
                                        <td>{{ $book->dataCategory->name }}</td>
                                        <td>{{ "Rp " . number_format($book->price,0,',','.') }}</td>
                                        <td>
                                            <div class="btn-toolbar" role="toolbar">
                                                <div class="btn-group mr-2" role="group">
                                                    <a class="btn btn-primary" href="{{ route('books.edit', $book->id) }}">Edit</a>
                                                </div>
                                                <div class="btn-group">
                                                    {{ Form::button('Delete', ['id' => 'button-delete-'. $book->id, 'class' => 'btn btn-danger', 'data-route' => route('books.destroy', $book->id) , 'onclick' => 'delete_data('. $book->id .')']) }}
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>

                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>

</div>
@endsection

@section('javascript')
    <script src="{{ asset('modules/datatables/datatables/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('modules/datatables/datatables/js/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('modules/sweetalert/sweetalert.min.js') }}"></script>
    <script type="text/javascript">
    var tableData;
    $(function() {
        @if ($message = Session::get('success'))
            toastr.success('{{ $message }}', 'Success');
        @endif

        tableData = $('#table-data').DataTable();

    });

    function delete_data(id)
    {
        var formUrl = $('#button-delete-'+ id).data('route');
        swal({
            title: 'Hapus Data?',
            text: 'Apakah yakin menghapus data?',
            buttons: {
                cancel: true,
                confirm: {
                    text: "Hapus!",
                    closeModal: false,
                }
            },
            dangerMode: true,
            closeOnClickOutside: false
        })
        .then((willDelete) => {
            if (willDelete) {
                 $.ajax({
                    headers: { 'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content') },
                    type: 'POST',
                    url : formUrl,
                    dataType: 'JSON',
                    data: {
                        '_token': '{{ csrf_token() }}',
                        '_method': 'DELETE',
                        'id': id,
                    },
                    success: function(res)
                    {
                        swal.stopLoading();
                        swal.close();
                        if(res.status == true)
                        {
                            toastr.success(res.message, 'Success');
                            location.reload();
                        }
                    },
                    error: function (jqXHR, textStatus, errorThrown)
                    {
                        swal.stopLoading();
                        swal.close();
                        toastr.error('Error deleted data', 'Error');
                    }
                });
            }
        });
    }
    </script>
@endsection