routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['prefix' => 'dashboard'], function() {
    Auth::routes([
        'register' => false,
        'reset' => false,
        'verify' => false,
    ]);
});

Route::get('/', 'WebsiteController@index');

Route::group(['middleware' => ['auth'], 'prefix' => 'dashboard'], function () {

    Route::get('/', 'HomeController@index')->name('dashboard');

    /**
     * Profile & User Route
     */
    Route::get('profile', 'UsersController@profile')->name('profile');
    Route::patch('profile/{user}', 'UsersController@profileUpdate')->name('profile.update');
    Route::resource('users', 'UsersController');

    /**
     * Roles & Permissions Administrator Route
     */
    Route::resource('roles', 'RolesController');
    Route::patch('permissions/sort-module', 'PermissionsController@sortModule')->name('permissions.sort-module');
    Route::resource('permissions', 'PermissionsController', ['except' => [
        'create', 'show', 'edit'
    ]]);

    Route::resource('categories', 'CategoriesController');
    Route::resource('books', 'BooksController');

});

app/Http/Controllers/RolesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\PermissionsLabel;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

use DB;

class RolesController extends Controller
{
    public function __construct() 
    {
        $this->middleware('permission:roles-list', ['only' => ['index', 'show']]);
        $this->middleware('permission:roles-create', ['only' => ['create', 'store']]);
        $this->middleware('permission:roles-edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:roles-delete', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $roles = Role::orderBy('fixed','DESC')
                    ->orderBy('name', 'ASC')
                    ->paginate(5);

        return view('backend.roles.index',compact('roles'))
            ->with('i', ($request->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permission = PermissionsLabel::orderBy('position', 'asc')
                                    ->with(['permission'])
                                    ->get();

        return view('backend.roles.create', compact('permission'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|unique:roles,name',
            'permission' => 'required',
        ]);

        $role = Role::create(['name' => $request->input('name')]);
        $role->syncPermissions($request->input('permission'));

        return redirect()->route('roles.index')
                        ->with('success','Level berhasil dibuat');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $role = Role::find($id);
        $permissions = PermissionsLabel::orderBy('position', 'asc')
                                    ->with(['permission' => function($query) use ($id){
                                            $query->join('role_has_permissions', 'role_has_permissions.permission_id', '=', 'permissions.id');
                                            $query->where('role_has_permissions.role_id', $id);
                                        }
                                    ])
                                    ->get();

        return view('backend.roles.show', compact('role', 'permissions'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = Role::find($id);
        $permission = PermissionsLabel::orderBy('position', 'asc')
                                    ->with(['permission'])
                                    ->get();
                                    
        $rolePermissions = DB::table('role_has_permissions')
                                ->where('role_has_permissions.role_id', $id)
                                ->pluck('role_has_permissions.permission_id', 'role_has_permissions.permission_id')
                                ->all();

        return view('backend.roles.edit', compact('role', 'permission', 'rolePermissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required|unique:roles,name,'. $id,
            'permission' => '',
        ]);

        $role = Role::find($id);
        $role->name = strtolower($request->input('name'));
        $role->save();

        if($role->fixed == 1) {
            $role->syncPermissions(Permission::all());
        }
        else {
            $role->syncPermissions($request->input('permission'));
        }

        return redirect()->route('roles.edit', $id)
                        ->with('success', 'Level berhasil diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $role = Role::findOrFail($id);
        if($role->fixed == 0) {
            $role->delete();
            return redirect()->route('roles.index')
                        ->with('success', 'Level berhasil dihapus');
        }
        else {
            return redirect()->route('roles.index')
                        ->with('error', 'Level tidak dapat dihapus');
        }
        
    }
}

resources/views/backend/roles/create.blade.php
@extends('layouts.app')

@section('title', 'Create New Role')

@section('content')
<div class="section-header">
    <div class="section-header-back">
        <a href="{{ route('roles.index') }}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
    </div>
    <h1>Buat Level Baru</h1>
</div>

<div class="section-body">

    {!! Form::open(['method'=>'POST', 'route' => 'roles.store', 'autocomplete'=>'off', 'class'=> 'needs-validation', 'novalidate'=> '']) !!}
    <div class="row">
        <div class="col-12">
            
            <div class="card">
                <div class="card-body">

                    @if (count($errors) > 0)
                        <div class="alert alert-danger">
                            <strong>Whoops!</strong> There were some problems with your input.<br><br>
                            <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                            </ul>
                        </div>
                    @endif

                    <div class="form-group row mb-0">
                        <label for="name" class="col-sm-3 col-form-label">Nama Level</label>
                        <div class="col-sm-9">
                            {!! Form::text('name', null, array('id' => 'name', 'placeholder' => 'Role Name', 'class' => 'form-control', 'required', 'autofocus')) !!}
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <div class="row">
        @foreach($permission as $perms)
        <div class="col-12 col-md-6 col-lg-3">
            <div class="card card-primary">
                <div class="card-header">
                    <h4>{{ $perms->label }}</h4>
                </div>
                @if(!empty($perms->permission))
                    <ul class="list-group list-group-flush">
                        @foreach($perms->permission as $value)
                            <li class="list-group-item">
                                <div class="custom-control custom-checkbox">
                                    {{ Form::checkbox('permission[]', $value->id, false, array('id' => 'role-'. $value->id , 'class' => 'custom-control-input')) }}
                                    <label for="role-{{ $value->id }}" class="custom-control-label">
                                        {{ ucwords(str_replace('-', ' ', $value->name)) }}
                                    </label>
                                </div>
                            </li>
                        @endforeach
                    </ul>
                @endif
            </div>
        </div>
        @endforeach
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body text-right">
                    <button type="submit" class="btn btn-lg btn-primary">Simpan</button>
                </div>
            </div>
        </div>
    </div>

    {!! Form::close() !!}

</div>

@endsection

resources/views/backend/roles/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit Level')

@section('content')
<div class="section-header">
    <div class="section-header-back">
        <a href="{{ route('roles.index') }}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
    </div>
    <h1>Edit Level</h1>
</div>

<div class="section-body">

    {!! Form::model($role, ['method' => 'PATCH', 'route' => ['roles.update', $role->id], 'autocomplete'=>'off', 'class'=> 'needs-validation', 'novalidate'=> '']) !!}
    <div class="row">
        <div class="col-12">

            <div class="card">
                <div class="card-body">

                    @if (count($errors) > 0)
                        <div class="alert alert-danger">
                            <strong>Whoops!</strong> There were some problems with your input.<br><br>
                            <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                            </ul>
                        </div>
                    @endif

                    <div class="form-group row mb-0">
                        <label for="name" class="col-sm-3 col-form-label">Nama Level</label>
                        <div class="col-sm-9">
                            @if($role->fixed == 0)
                            {!! Form::text('name', null, array('id' => 'name', 'placeholder' => 'Role Name', 'class' => 'form-control', 'required', 'autofocus')) !!}
                            @else
                            {!! Form::text('name', null, array('id' => 'name', 'class' => 'form-control-plaintext', 'required')) !!}
                            @endif
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <div class="row">
        @foreach($permission as $perms)
        <div class="col-12 col-md-6 col-lg-3">
            <div class="card card-primary">
                <div class="card-header">
                    <h4>{{ $perms->label }}</h4>
                </div>
                @if(!empty($perms->permission))
                    <ul class="list-group list-group-flush">
                        @foreach($perms->permission as $value)
                            <li class="list-group-item">
                                <div class="custom-control custom-checkbox">
                                    {{ Form::checkbox('permission[]', $value->id, in_array($value->id, $rolePermissions) ? true : false, array('id' => 'role-'. $value->id , 'class' => 'custom-control-input')) }}
                                    <label for="role-{{ $value->id }}" class="custom-control-label">
                                        {{ ucwords(str_replace('-', ' ', $value->name)) }}
                                    </label>
                                </div>
                            </li>
                        @endforeach
                    </ul>
                @endif
            </div>
        </div>
        @endforeach
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body text-right">
                    <button type="submit" class="btn btn-lg btn-primary">Simpan</button>
                </div>
            </div>
        </div>
    </div>
    {!! Form::close() !!}

</div>

@endsection

@section('javascript')
    @if ($message = Session::get('success'))
        <script type="text/javascript">
            toastr.success('{{ $message }}', 'Success');
        </script>
    @endif
@endsection

resources/views/backend/roles/index.blade.php
@extends('layouts.app')

@section('title', 'Manajemen Level')

@section('content')
<div class="section-header">
    <h1>Manajemen Level</h1>

    <div class="section-header-button ml-auto">
        @can('roles-create')
        <a class="btn btn-primary" href="{{ route('roles.create') }}">
            Buat Level
        </a>
        @endcan
        @role('superadmin')
        <a class="btn btn-primary" href="{{ route('permissions.index') }}">
            Manajemen Hak Akses
        </a>
        @endrole
    </div>
</div>

<div class="section-body">
    <div class="row">
        <div class="col-12">

            <div class="card">
                <div class="card-body p-0">
                    
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <tr>
                                <th width="50px">No.</th>
                                <th>Nama</th>
                                <th width="30%">&nbsp;</th>
                            </tr>
                            @foreach ($roles as $key => $role)
                            <tr>
                                <td>{{ ++$i }}</td>
                                <td>
                                    @if($role->fixed == 1)
                                        <div class="badge badge-primary">{{ ucfirst($role->name) }}</div>
                                    @else
                                        {{ ucfirst($role->name) }}
                                    @endif
                                </td>
                                <td>
                                    <div class="btn-toolbar" role="toolbar">
                                        <div class="btn-group mr-2" role="group">
                                            <a class="btn btn-outline-primary" href="{{ route('roles.show',$role->id) }}">Detail</a>
                                            @can('roles-edit')
                                                <a class="btn btn-primary" href="{{ route('roles.edit', $role->id) }}">Edit</a>
                                            @endcan
                                        </div>
                                        @if($role->fixed == 0)
                                        @can('roles-delete')
                                        <div class="btn-group">
                                            {!! Form::open(['method' => 'DELETE','route' => ['roles.destroy', $role->id], 'style' => 'display:inline', 'id' => 'delete-'. $role->id]) !!}
                                            {!! Form::submit('Delete', ['class' => 'btn btn-danger', 'data-confirm'=> 'Perhatian!|Anda yakin ingin mengahpus data ini?', 'data-confirm-yes'=>'document.getElementById(\'delete-'. $role->id .'\').submit()']) !!}
                                            {!! Form::close() !!}
                                        </div>
                                        @endcan
                                        @endif
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </table>
                    </div>
                </div>
                <div class="card-footer text-right">
                    <nav class="d-inline-block">
                        {!! $roles->render() !!}
                    </nav>
                </div>
            </div>

        </div>
    </div>
</div>

@endsection

@section('javascript')
<script type="text/javascript">
    @if ($message = Session::get('success'))
        toastr.success('{{ $message }}', 'Sukses');
    @elseif($message = Session::get('error'))
        toastr.error('{{ $message }}', 'Gagal');
    @endif
</script>
@endsection

resources/views/backend/roles/show.blade.php
@extends('layouts.app')

@section('title', 'Detail Level')

@section('content')
<div class="section-header">
    <div class="section-header-back">
        <a href="{{ route('roles.index') }}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
    </div>
    <h1>{{ ucwords($role->name) }}</h1>
    <div class="section-header-button ml-auto">
        @can('roles-edit')
            <a class="btn btn-primary" href="{{ route('roles.edit', $role->id) }}">Edit</a>
        @endcan
    </div>
</div>

<div class="section-body">

    <div class="row">
        @foreach($permissions as $perms)
        <div class="col-12 col-md-6 col-lg-3">
            <div class="card {{ count($perms->permission) > 0 ? 'card-primary' : '' }}">
                <div class="card-header">
                    <h4>{{ $perms->label }}</h4>
                </div>
                @if(!empty($perms->permission))
                    <ul class="list-group list-group-flush">
                        @foreach($perms->permission as $v)
                            <li class="list-group-item">
                                <i class="ion ion-checkmark-round mr-2"></i>
                                {{ ucwords(str_replace('-', ' ', $v->name)) }}
                            </li>
                        @endforeach
                    </ul>
                @endif
            </div>
        </div>
        @endforeach
    </div>

</div>
@endsection