routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['prefix' => 'dashboard'], function() {
    Auth::routes([
        'register' => false,
        'reset' => false,
        'verify' => false,
    ]);
});

Route::get('/', 'WebsiteController@index');

Route::group(['middleware' => ['auth'], 'prefix' => 'dashboard'], function () {

    Route::get('/', 'HomeController@index')->name('dashboard');

    /**
     * Profile & User Route
     */
    Route::get('profile', 'UsersController@profile')->name('profile');
    Route::patch('profile/{user}', 'UsersController@profileUpdate')->name('profile.update');
    Route::resource('users', 'UsersController');

    /**
     * Roles & Permissions Administrator Route
     */
    Route::resource('roles', 'RolesController');
    Route::patch('permissions/sort-module', 'PermissionsController@sortModule')->name('permissions.sort-module');
    Route::resource('permissions', 'PermissionsController', ['except' => [
        'create', 'show', 'edit'
    ]]);

    Route::resource('categories', 'CategoriesController');
    Route::resource('books', 'BooksController');

});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title') &mdash; {{ config('app.name') }}</title>

    <link rel="apple-touch-icon" sizes="57x57" href="{{ asset('favicon/apple-icon-57x57.png') }}">
    <link rel="apple-touch-icon" sizes="60x60" href="{{ asset('favicon/apple-icon-60x60.png') }}">
    <link rel="apple-touch-icon" sizes="72x72" href="{{ asset('favicon/apple-icon-72x72.png') }}">
    <link rel="apple-touch-icon" sizes="76x76" href="{{ asset('favicon/apple-icon-76x76.png') }}">
    <link rel="apple-touch-icon" sizes="114x114" href="{{ asset('favicon/apple-icon-114x114.png') }}">
    <link rel="apple-touch-icon" sizes="120x120" href="{{ asset('favicon/apple-icon-120x120.png') }}">
    <link rel="apple-touch-icon" sizes="144x144" href="{{ asset('favicon/apple-icon-144x144.png') }}">
    <link rel="apple-touch-icon" sizes="152x152" href="{{ asset('favicon/apple-icon-152x152.png') }}">
    <link rel="apple-touch-icon" sizes="180x180" href="{{ asset('favicon/apple-icon-180x180.png') }}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{{ asset('favicon/android-icon-192x192.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ asset('favicon/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="96x96" href="{{ asset('favicon/favicon-96x96.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ asset('favicon/favicon-16x16.png') }}">
    <link rel="manifest" href="{{ asset('favicon/manifest.json') }}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{{ asset('favicon/ms-icon-144x144.png') }}">
    <meta name="theme-color" content="#ffffff">

    <link rel="stylesheet" href="{{ asset('modules/bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('modules/fontawesome/css/all.min.css') }}">

    @yield('styles')

    <link rel="stylesheet" href="{{ asset('css/style.css') }}">
    <link rel="stylesheet" href="{{ asset('css/components.css') }}">

</head>
<body id="silhouette-bg">
    <div id="app">
        <div class="main-wrapper main-wrapper-1">
            @include('layouts.navbar')
            @include('layouts.sidebar')

            <div class="main-content">
                <section class="section">
                    @yield('content')
                </section>
            </div>

            <footer class="main-footer">
                <div class="footer-left">
                    Copyright &copy; 2021 UAS <div class="bullet"></div> FrameWork
                </div>
            </footer>

        </div>
    </div>

    @stack('modals')

    <script src="{{ asset('modules/jquery.min.js' ) }}"></script>
    <script src="{{ asset('modules/popper.js' ) }}"></script>
    <script src="{{ asset('modules/tooltip.js' ) }}"></script>
    <script src="{{ asset('modules/bootstrap/js/bootstrap.min.js' ) }}"></script>
    <script src="{{ asset('modules/nicescroll/jquery.nicescroll.min.js' ) }}"></script>
    <script src="{{ asset('modules/moment.min.js' ) }}"></script>
    <script src="{{ asset('modules/toastr.min.js' ) }}"></script>
    <script src="{{ asset('js/stisla.js' ) }}"></script>
    <script src="{{ asset('js/scripts.js') }}"></script>

    @yield('javascript')
</body>
</html>

resources/views/layouts/navbar.blade.php
<div class="navbar-bg"></div>
<nav class="navbar navbar-expand-lg main-navbar">
    <div class="">
        <ul class="navbar-nav mr-3">
            <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
        </ul>
    </div>
    <div class="navbar-brand mb-0 d-none d-md-block">
        <h1>MT.com Dashboard</h1>
    </div>
    <div class="navbar-brand mb-0 mr-0 d-md-none">
        <h1>MT.com</h1>
    </div>
    <ul class="navbar-nav navbar-right ml-auto">
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                @if($avatar = Auth::user()->avatar)
                    <img alt="image" src="{{ asset('uploads/avatars/'. $avatar )}}" width="30" class="rounded-circle mr-1">
                @else
                    <i class="fas fa-fw fa-user-circle"></i>
                @endif
                <div class="d-sm-none d-lg-inline-block">{{ Auth::user()->name }}</div>

            </a>
            <div class="dropdown-menu dropdown-menu-right">
                <div class="dropdown-title">Logged in {{ Carbon\Carbon::parse(Auth::user()->last_login_at)->diffForHumans() }}</div>
                <a href="{{ route('profile') }}" class="dropdown-item has-icon">
                    <i class="far fa-user"></i> Profile
                </a>
                <div class="dropdown-divider"></div>
                <a href="{{ route('logout') }}" class="dropdown-item has-icon text-danger" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                    <i class="fas fa-sign-out-alt"></i> Logout
                </a>
                <form id="logout-form" class="d-none" action="{{ route('logout') }}" method="POST">
                    @csrf
                </form>
            </div>
        </li>
    </ul>
</nav>

resources/views/layouts/sidebar.blade.php
<div class="main-sidebar">
    <aside id="sidebar-wrapper">
        <div class="sidebar-brand">
            <a href="{{ route('dashboard') }}">
                <img src="{{ asset('images/logo-small.png')}}" alt="handlebrand">
                <span class="ml-1 text-primary">MT.com</span>
            </a>
        </div>
        <div class="sidebar-brand sidebar-brand-sm">
            <a href="{{ route('dashboard') }}">
                <img src="{{ asset('images/logo-small.png')}}" alt="handlebrand">
            </a>
        </div>
        <ul class="sidebar-menu">
            <li {!! request()->routeIs('dashboard') == true ? 'class="active"' : null !!}>
                <a class="nav-link" href="{{ route('dashboard') }}"><i class="fas fa-fire"></i> <span>Dashboard</span></a>
            </li>

            <li class="menu-header">Master Data</li>
            @can('books-list')
                <li {!! request()->routeIs('books*') == true ? 'class="active"' : null !!}>
                    <a href="{{ route('books.index') }}" class="nav-link"><i class="fas fa-book"></i> <span>Data Buku</span></a>
                </li>
            @endcan
            @can('categories-list')
                <li {!! request()->routeIs('categories*') == true ? 'class="active"' : null !!}>
                    <a href="{{ route('categories.index') }}" class="nav-link"><i class="fas fa-list-ul"></i> <span>Data Kategori</span></a>
                </li>
            @endcan


            @if(Auth::user()->can('users-list') || Auth::user()->can('roles-list'))
                <li class="menu-header">Pengaturan</li>
                    @can('users-list')
                        <li {!! request()->routeIs('users*') == true ? 'class="active"' : null !!}>
                            <a href="{{ route('users.index') }}" class="nav-link"><i class="far fa-id-badge"></i> <span>Administrator</span></a>
                        </li>
                    @endcan

                    @can('roles-list')
                        <li {!! request()->routeIs('roles*') == true ? 'class="active"' : null !!}>
                            <a href="{{ route('roles.index') }}" class="nav-link"><i class="fas fa-user-shield"></i> <span>Level Administrator</span></a>
                        </li>
                    @endcan
            @endif
        </ul>
    </aside>
</div>